"""initial schema

Revision ID: 0447ea3a668f
Revises: 
Create Date: 2026-09-25 08:06:54.664253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0447ea3a668f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('connected_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('strava', 'intervals_icu', 'trainingpeaks', name='provider', native_enum=False, length=32), nullable=False),
    sa.Column('provider_athlete_id', sa.String(length=64), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes_granted', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connected_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connected_accounts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_active_athlete_per_provider', ['provider', 'provider_athlete_id'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
        batch_op.create_index('uq_active_provider_per_user', ['user_id', 'provider'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))

    op.create_table('planned_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structure', sa.JSON(), nullable=True),
    sa.Column('source_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_event_id', name='uq_planned_workout_source_event')
    )
    with op.batch_alter_table('planned_workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_workouts_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_workouts_user_id'), ['user_id'], unique=False)

    op.create_table('activity_debriefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planned_workout_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.Enum('strava', 'intervals_icu', 'trainingpeaks', name='provider', native_enum=False, length=32), nullable=False),
    sa.Column('provider_activity_id', sa.String(length=64), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['planned_workout_id'], ['planned_workouts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_activity_id', name='uq_debrief_activity')
    )
    with op.batch_alter_table('activity_debriefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_debriefs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_debriefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_debriefs_user_id'))

    op.drop_table('activity_debriefs')
    with op.batch_alter_table('planned_workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_workouts_user_id'))
        batch_op.drop_index(batch_op.f('ix_planned_workouts_scheduled_date'))

    op.drop_table('planned_workouts')
    with op.batch_alter_table('connected_accounts', schema=None) as batch_op:
        batch_op.drop_index('uq_active_provider_per_user', sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
        batch_op.drop_index('uq_active_athlete_per_provider', sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_connected_accounts_user_id'))

    op.drop_table('connected_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
